### ISSUE TITLE
肖同学你好，咨询一下raindrop的指标问题

### ISSUE THREAD

**Issue by zhangbaijin** [jiexiaou/IDT#1]
你好，我用了您的raindrop的测试指标，用的是raindrop的test_b，我用的MPRNet的网络，测出来PSNR是24-25，ssim是0.8样子，您论文里的数据RainDS-Real的RD是对应的rain drop的测试指标吗？为什么ssim普遍比较低？

**Comment by jiexiaou** [comment]
您好，raindrop的结果在Tab 4，所用的测试集是由test_a进一步切的128*128的图像块，我们也公开了全图的结果。

**Comment by 1577148518** [comment]
您好，请问您是否能开源一下针对full-size图片的测试代码呢？
